### PR TITLE
Triangular Linear Systems

### PR DESCRIPTION
**Pull request by caroott**
Add unit tests covering:
- LinearAlgebraManaged.SolveTriangularLinearSystems
- LinearAlgebraManaged.SolveTriangularLinearSystem

Reference implementation:
[R package "bdsmatrix: Routines for Block Diagonal Symmetric Matrices" Version 1.3-6](https://cran.r-project.org/web/packages/bdsmatrix/index.html)

### CODE REVIEW

**Comment by kMutagene** [comment]
Can you please add at least 1 more "real world example"? IIRC you are only usung a 3x3 matrix with 1/0/eddge-cases. I would suggest to add at least one "real" system of equations to solve

**Comment by kMutagene** [comment]
Also, since you dove deep into the topic, i'd love some explanatory xml docs on top of the functions

**Comment by bvenn** [comment]
Did you try to call the function with non-square (over/underdetermined) matrices?

**Comment by caroott** [comment]
@bvenn  A triangular matrix is a kind of square matrix. The matrix dimensions are checked [here](https://github.com/fslaborg/FSharp.Stats/blob/5837ae88d56424912a47bb78558b54c5c09e7c49/src/FSharp.Stats/Algebra/LinearAlgebraServiceManaged.fs#L44). When a non-square matrix is given, an exception is thrown.

**Review by bvenn — APPROVED** [review]

**Pull request merged**
